### ISSUE TITLE
bug: Tail logfiles with a webhook has inconsistent pod names / wrong snippets

### ISSUE THREAD

**Issue by OverOrion** [kube-logging/kube-logging.github.io#187]
https://kube-logging.dev/4.2/docs/configuration/extensions/tailer-webhook/

The following things should be fixed:

- [ ] File tailer example has a second container which is not needed, the snippet's indentation is not right either
- [ ] `kubectl get pod test-pod -o json | jq '.spec.containers | map(.name)'` output should be the actual output
- [ ] `kubectl logs test-pod test; echo $?` should use the actual name and it's output should have a few more lines
- [ ] Using the annotation for the `caBundle` injection as mentioned above it:
>For example: you can inject the CA with a simple cert-manager cert-manager.io/inject-ca-from: logging/webhook-tls annotation on the mutatingwebhookconfiguration resource.

Like this:
```
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sample-webhook-cfg
  namespace: logging
  labels:
    app: sample-webhook
  annotations:
    cert-manager.io/inject-ca-from: logging/webhook-tls
webhooks:
  - name: sample-webhook.banzaicloud.com
    clientConfig:
      service:
        name: logging-webhooks
        namespace: logging
        path: "/tailer-webhook"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "*"
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: [v1]
```

- [ ] We should also expand it with a section that describes using the cert-manager to issue a simple certificate.
