### ISSUE TITLE
syslog-ng clusteroutput TLS not working

### ISSUE THREAD

**Issue by busyboy77** [kube-logging/kube-logging.github.io#212]
cluster output manifest

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGClusterOutput
metadata:
 name: loki-output
 namespace: logging
spec:
  loki:
    url: https://devops249.ef.com/loki/api/v1/push
    labels:
      "app_kubernetes_io_name": "${json#kubernetes#labels#app.kubernetes.io/name}"
      "app_kubernetes_io_instance": "${json#kubernetes#labels#app.kubernetes.io/instance}"
      "app_kubernetes_io_component": "${json#kubernetes#labels#app.kubernetes.io/component}"
      "namespace_name": ${json#kubernetes#namespace_name}
      "pod_name": ${json#kubernetes#pod_name}
    timestamp: "msg"
    template: "$ISODATE $HOST $MSGHDR$MSG"
    auth:
      insecure: {}
      tls:
         peer_verify: false

```

get the pods

```
root@devops248:/tmp# k -n logging get pods
NAME                                               READY   STATUS      RESTARTS   AGE
logging-operator-ff99697f7-2hj7h                   1/1     Running     0          26h
logging-operator-ff99697f7-htpx5                   1/1     Running     0          26h
logging-operator-ff99697f7-rm5w6                   1/1     Running     0          26h
logging-operator-ff99697f7-wbnxl                   1/1     Running     0          26h
logging-operator-ff99697f7-xwjsn                   1/1     Running     0          26h
syslog-ng-logging-fluentbit-pk45j                  1/1     Running     0          3h26m
syslog-ng-logging-syslog-ng-0                      2/2     Running     0          3h26m
syslog-ng-logging-syslog-ng-configcheck-b947403f   0/1     Error       0          5s
syslog-ng-logging-syslog-ng-configcheck-f0aad5ab   0/1     Completed   0          2m1s
```

logs for the config pod 
```
root@devops248:/tmp# k -n logging logs -f syslog-ng-logging-syslog-ng-configcheck-b947403f
Setting current version as config version; version='4.5'
Error parsing within destination, syntax error, unexpected KW_TLS, expecting ')' in /etc/syslog-ng/config/syslog-ng.conf:18:26-18:29:
13              };
14          };
15      };
16
17      destination "clusteroutput_logging_loki-output" {
18---->     loki(auth(insecure() tls(peer_verify(no))) labels(
18---->                          ^^^
19              "app_kubernetes_io_component" => "${json#kubernetes#labels#app.kubernetes.io/component}"
20              "app_kubernetes_io_instance" => "${json#kubernetes#labels#app.kubernetes.io/instance}"
21              "app_kubernetes_io_name" => "${json#kubernetes#labels#app.kubernetes.io/name}"
22              "namespace_name" => "${json#kubernetes#namespace_name}"
23              "pod_name" => "${json#kubernetes#pod_name}"

```

however the CRDS say this is an object under the loki's 
[link to CRD object](
https://doc.crds.dev/github.com/kube-logging/logging-operator/logging.banzaicloud.io/SyslogNGClusterOutput/v1beta1@4.5.0#spec-loki-auth-tls-peer_verify)
